import dynamic from "next/dynamic";
import type { ComponentType } from "react";
import { Processing } from "../ToolShell";

// Every tool mounts client-side only (ssr:false): the heavy engines
// (pdf-lib, pdfjs, exceljs, docx, heic2any…) move off the critical path and
// load as their own async chunk only after hydration. The tool widget is a
// client-only interactive UI; SEO content already lives in the page and its
// structured data, so nothing loses value by skipping server HTML for it.
const lazy = (loader: () => Promise<{ default: ComponentType }>) =>
  dynamic(loader, { ssr: false, loading: () => <Processing /> });

export const TOOL_COMPONENTS: Record<string, ComponentType> = {
  MergePdf: lazy(() => import("./MergePdf")),
  SplitPdf: lazy(() => import("./SplitPdf")),
  RotatePdf: lazy(() => import("./RotatePdf")),
  DeletePdfPages: lazy(() => import("./DeletePdfPages")),
  JpgToPdf: lazy(() => import("./JpgToPdf")),
  PdfToJpg: lazy(() => import("./PdfToJpg")),
  CompressPdf: lazy(() => import("./CompressPdf")),
  CompressImage: lazy(() => import("./CompressImage")),
  ResizeImage: lazy(() => import("./ResizeImage")),
  ConvertImage: lazy(() => import("./ConvertImage")),
  HeicToJpg: lazy(() => import("./HeicToJpg")),
  RotateImage: lazy(() => import("./RotateImage")),
  RemoveExif: lazy(() => import("./RemoveExif")),
  WordCounter: lazy(() => import("./WordCounter")),
  CaseConverter: lazy(() => import("./CaseConverter")),
  PasswordGenerator: lazy(() => import("./PasswordGenerator")),
  QrGenerator: lazy(() => import("./QrGenerator")),
  JsonFormatter: lazy(() => import("./JsonFormatter")),
  Base64Tool: lazy(() => import("./Base64Tool")),
  RemoveTashkeel: lazy(() => import("./RemoveTashkeel")),
  ArabicNumerals: lazy(() => import("./ArabicNumerals")),
  HijriGregorian: lazy(() => import("./HijriGregorian")),
  ReorderPdf: lazy(() => import("./ReorderPdf")),
  WatermarkPdf: lazy(() => import("./WatermarkPdf")),
  PageNumbersPdf: lazy(() => import("./PageNumbersPdf")),
  CropImage: lazy(() => import("./CropImage")),
  CircleCrop: lazy(() => import("./CircleCrop")),
  BlurImage: lazy(() => import("./BlurImage")),
  ImageFilters: lazy(() => import("./ImageFilters")),
  ImageToBase64: lazy(() => import("./ImageToBase64")),
  FaviconGenerator: lazy(() => import("./FaviconGenerator")),
  ColorPicker: lazy(() => import("./ColorPicker")),
  SvgToPng: lazy(() => import("./SvgToPng")),
  IdPhoto: lazy(() => import("./IdPhoto")),
  UrlEncode: lazy(() => import("./UrlEncode")),
  UuidGenerator: lazy(() => import("./UuidGenerator")),
  HashGenerator: lazy(() => import("./HashGenerator")),
  RemoveDuplicateLines: lazy(() => import("./RemoveDuplicateLines")),
  TextDiff: lazy(() => import("./TextDiff")),
  LoremIpsum: lazy(() => import("./LoremIpsum")),
  MarkdownToHtml: lazy(() => import("./MarkdownToHtml")),
  CsvJson: lazy(() => import("./CsvJson")),
  Tafqit: lazy(() => import("./Tafqit")),
  ExtractPdfPages: lazy(() => import("./ExtractPdfPages")),
  PdfToText: lazy(() => import("./PdfToText")),
  PdfToExcel: lazy(() => import("./PdfToExcel")),
  PdfToWord: lazy(() => import("./PdfToWord")),
  PngToPdf: lazy(() => import("./PngToPdf")),
  PdfMetadata: lazy(() => import("./PdfMetadata")),
  GrayscalePdf: lazy(() => import("./GrayscalePdf")),
  FlipImage: lazy(() => import("./FlipImage")),
  PngToJpg: lazy(() => import("./PngToJpg")),
  WebpToJpg: lazy(() => import("./WebpToJpg")),
  JpgToWebp: lazy(() => import("./JpgToWebp")),
  AddTextToImage: lazy(() => import("./AddTextToImage")),
  PixelateImage: lazy(() => import("./PixelateImage")),
  RoundCorners: lazy(() => import("./RoundCorners")),
  ReverseText: lazy(() => import("./ReverseText")),
  TextToSlug: lazy(() => import("./TextToSlug")),
  BinaryText: lazy(() => import("./BinaryText")),
  MorseCode: lazy(() => import("./MorseCode")),
  NumberBase: lazy(() => import("./NumberBase")),
  RomanNumerals: lazy(() => import("./RomanNumerals")),
  RandomNumber: lazy(() => import("./RandomNumber")),
  ColorConverter: lazy(() => import("./ColorConverter")),
  CssMinifier: lazy(() => import("./CssMinifier")),
  HtmlEncode: lazy(() => import("./HtmlEncode")),
  TimestampConverter: lazy(() => import("./TimestampConverter")),
  SortLines: lazy(() => import("./SortLines")),
  FindReplace: lazy(() => import("./FindReplace")),
  Mt940ToExcel: lazy(() => import("./Mt940ToExcel")),
  ExcelToMt940: lazy(() => import("./ExcelToMt940")),
  TxtToMt940: lazy(() => import("./TxtToMt940")),
  InvoiceGenerator: lazy(() => import("./InvoiceGenerator")),
  CvBuilder: lazy(() => import("./CvBuilder")),
  FlattenPdf: lazy(() => import("./FlattenPdf")),
  CropPdf: lazy(() => import("./CropPdf")),
  CodeSnippet: lazy(() => import("./CodeSnippet")),
  Handwriting: lazy(() => import("./Handwriting")),
  GhostText: lazy(() => import("./GhostText")),
  Steganography: lazy(() => import("./Steganography")),
  FileXray: lazy(() => import("./FileXray")),
  ExcelToCsv: lazy(() => import("./ExcelToCsv")),
  CsvToExcel: lazy(() => import("./CsvToExcel")),
  ExcelToJson: lazy(() => import("./ExcelToJson")),
  JsonToExcel: lazy(() => import("./JsonToExcel")),
  ArabicKeyboard: lazy(() => import("./ArabicKeyboard")),
  ArabicTransliteration: lazy(() => import("./ArabicTransliteration")),
  ZakatCalculator: lazy(() => import("./ZakatCalculator")),
  AgeCalculator: lazy(() => import("./AgeCalculator")),
  OrganizePdf: lazy(() => import("./OrganizePdf")),
  ImagesToPdf: lazy(() => import("./ImagesToPdf")),
  ProtectPdf: lazy(() => import("./ProtectPdf")),
  PdfRedaction: lazy(() => import("./PdfRedaction")),
  PdfEditor: lazy(() => import("./PdfEditor")),
  PdfToAudio: lazy(() => import("./PdfToAudio")),
  DocumentScanner: lazy(() => import("./DocumentScanner")),
  QrWithLogo: lazy(() => import("./QrWithLogo")),
  CertificateGenerator: lazy(() => import("./CertificateGenerator")),
  LetterGenerator: lazy(() => import("./LetterGenerator")),
  IdCardGenerator: lazy(() => import("./IdCardGenerator")),
};
