import {
  Merge,
  Split,
  RotateCw,
  Rows3,
  FileOutput,
  Crop,
  Layers,
  FileInput,
  ArrowLeftRight,
  AudioLines,
  AudioWaveform,
  Download,
  Stamp,
  Hash,
  BoxSelect,
  ListFilter,
  ScanLine,
  ShieldCheck,
  FilePenLine,
  FileCog,
  FileImage,
  DollarSign,
  Scan,
  Undo2,
  Circle,
  FileType,
  IdCard,
  ScanFace,
  ImageDown,
  Code2,
  Image,
  Binary,
  Eraser,
  Bird,
  Wand2,
  Baseline,
  List,
  CaseSensitive,
  Replace,
  ArrowUpDown,
  TextCursorInput,
  Link,
  FileDiff,
  CopyPlus,
  FileText,
  FileKey2,
  QrCode,
  CalendarDays,
  FileBadge,
  Ghost,
  Braces,
  MinusSquare,
  FileCode2,
  TerminalSquare,
  Globe,
  Table,
  Banknote,
  Waypoints,
  Sigma,
  Dices,
  Palette,
  Clock3,
  FileCode,
  FileStack,
  Coins,
  Type,
  Keyboard,
  Wallet,
  FileX,
  FileArchive,
  HandHeart,
  Shield,
  Receipt,
  UserRound,
  Mail,
  PenLine,
  Proportions,
  type LucideProps,
} from "lucide-react";
import { ComponentType } from "react";

interface Props { icon: string; color?: string; size?: number }

// icon key (from tools.ts) -> Lucide component. Professional, consistent set.
const ICONS: Record<string, ComponentType<LucideProps>> = {
  merge: Merge,
  split: Split,
  rotate: RotateCw,
  "rotate-cw": RotateCw,
  delete: FileX,
  reorder: Rows3,
  extract: FileOutput,
  crop: Crop,
  "crop-img": Crop,
  flatten: Layers,
  img2pdf: FileInput,
  pdf2img: FileOutput,
  convert: ArrowLeftRight,
  text2speech: AudioLines,
  audio: AudioWaveform,
  compress: Download,
  watermark: Stamp,
  numbers: Hash,
  grayscale: BoxSelect,
  filters: ListFilter,
  info: ScanLine,
  layout: Rows3,
  shield: ShieldCheck,
  redact: FilePenLine,
  edit: FileCog,
  resize: Scan,
  flip: Undo2,
  circle: Circle,
  round: FileType,
  id: IdCard,
  idcard: IdCard,
  scanner: ScanFace,
  "image-convert": ImageDown,
  code: Code2,
  image: Image,
  "compress-img": FileArchive,
  "remove-exif": Eraser,
  blur: Bird,
  "image-filters": Wand2,
  "text-overlay": Baseline,
  pixelate: BoxSelect,
  picker: HandHeart,
  stego: Shield,
  favicon: FileImage,
  count: List,
  case: CaseSensitive,
  replace: Replace,
  sort: ArrowUpDown,
  "flip-text": TextCursorInput,
  link: Link,
  diff: FileDiff,
  dedupe: CopyPlus,
  lorem: FileText,
  key: FileKey2,
  "key-round": FileKey2,
  qr: QrCode,
  calendar: CalendarDays,
  invoice: Receipt,
  cv: UserRound,
  cert: FileBadge,
  letter: Mail,
  ghost: Ghost,
  pen: PenLine,
  braces: Braces,
  binary: Binary,
  minimize: MinusSquare,
  "file-code": FileCode2,
  terminal: TerminalSquare,
  url: Globe,
  table: Table,
  bank: Banknote,
  algo: Waypoints,
  hash: Hash,
  morse: AudioWaveform,
  "number-base": Sigma,
  dice: Dices,
  palette: Palette,
  clock: Clock3,
  "code-snip": FileCode,
  xray: FileStack,
  coin: Coins,
  "text-ar": Type,
  "ar-numerals": Hash,
  hijri: CalendarDays,
  tafqit: DollarSign,
  keyboard: Keyboard,
  transliterate: Proportions,
  zakat: Wallet,
};

export function ToolIcon({ icon, color, size = 26 }: Props) {
  const Icon = ICONS[icon] ?? FileText;
  return (
    <Icon
      width={size}
      height={size}
      strokeWidth={1.8}
      aria-hidden
      color={color ?? "currentColor"}
      absoluteStrokeWidth
    />
  );
}
